//! Emit Cargo.toml and the lib.rs header / footer for a generated extension crate.

use crate::yaml::model::ValidatedExtension;

pub fn emit_cargo_toml(ext: &ValidatedExtension, embedded_bytes: bool) -> String {
    let id = &ext.id;
    let features = if embedded_bytes {
        String::new()
    } else {
        ", features = [\"builder\"]".into()
    };
    format!(
        r#"[package]
name = "kani-{id}"
version = "{version}"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
kani-shared = {{ path = "../../kani-shared"{features} }}

[package.metadata]
id = "{id}"
"#,
        version = ext.version,
    )
}

pub fn emit_lib_header(ext: &ValidatedExtension, embedded_bytes: bool) -> String {
    let struct_name = to_pascal_case(&ext.id);
    let base_url = &ext.base_url;
    let id = &ext.id;
    let name = &ext.name;
    let version = &ext.version;
    let language = &ext.language;
    let nsfw = ext.nsfw;
    let unrestricted_http = ext.unrestricted_http;
    let mihon_source_id = match ext.mihon_source_id {
        Some(n) => format!("Some({n}_i64)"),
        None => "None".to_string(),
    };

    let pref_import = if ext.preferences.is_empty() {
        ""
    } else {
        ", preference_list"
    };

    let extract_import = if embedded_bytes {
        "use kani_shared::host_abi::{HttpRequest, extract_raw};"
    } else {
        "use kani_shared::host_abi::{HttpRequest, extract};"
    };

    let ast_import = if embedded_bytes {
        String::new()
    } else {
        "use kani_shared::ast::{BlueprintBuilder, Expr, OffsetType};\n".into()
    };

    format!(
        r#"// @generated by kani-cli from {id}.yaml — edit freely, but regenerate with `kani-cli generate` to reset.

use std::sync::OnceLock;
use kani_shared::bindings::exports::kani::extension::manga_provider::Guest;
{extract_import}
use kani_shared::{{
    ExtensionResult, MangaExtension, MangaStatus, bindings, wit_types,
    types::ActiveFilter, to_shared_filters, filter_list{pref_import}, FilterState,
}};
{ast_import}use wit_types::{{Chapter, ChapterList, ChapterInfo, ExtensionMetadata, MangaInfo, MangaList, MangaListItem, Page, PreferenceSpec}};

kani_shared::guest_alloc!();

pub struct {struct_name} {{
    base_url: String,
}}

impl Default for {struct_name} {{
    fn default() -> Self {{ Self::new() }}
}}

impl {struct_name} {{
    pub fn new() -> Self {{
        Self {{ base_url: "{base_url}".to_string() }}
    }}

    pub fn metadata() -> ExtensionMetadata {{
        ExtensionMetadata {{
            id:               "{id}".to_string(),
            name:             "{name}".to_string(),
            version:          "{version}".to_string(),
            base_url:         "{base_url}".to_string(),
            language:         "{language}".to_string(),
            nsfw:             {nsfw},
            unrestricted_http: {unrestricted_http},
            mihon_source_id:  {mihon_source_id},
        }}
    }}
}}
"#
    )
}

pub fn emit_guest_impl(ext: &ValidatedExtension) -> String {
    let struct_name = to_pascal_case(&ext.id);

    let popular_impl: String = if ext.popular.is_some() {
        "    fn get_popular_manga(page: i32, page_size: i32, filters: Vec<wit_types::ActiveFilter>) -> Result<MangaList, wit_types::ExtensionError> {\n\
         let shared = to_shared_filters(filters);\n\
         get_extension().get_popular_manga(page, page_size, &shared).map_err(|e| e.into_wit())\n\
         }\n".to_string()
    } else {
        "    fn get_popular_manga(_page: i32, _page_size: i32, _filters: Vec<wit_types::ActiveFilter>) -> Result<MangaList, wit_types::ExtensionError> {\n\
         Ok(MangaList { manga: vec![], has_next_page: false })\n\
         }\n".to_string()
    };

    let search_impl: String = if ext.search.is_some() {
        "    fn search_manga(query: String, page: i32, page_size: i32, filters: Vec<wit_types::ActiveFilter>) -> Result<MangaList, wit_types::ExtensionError> {\n\
         let shared = to_shared_filters(filters);\n\
         get_extension().search_manga(&query, page, page_size, &shared).map_err(|e| e.into_wit())\n\
         }\n".to_string()
    } else {
        "    fn search_manga(_query: String, _page: i32, _page_size: i32, _filters: Vec<wit_types::ActiveFilter>) -> Result<MangaList, wit_types::ExtensionError> {\n\
         Ok(MangaList { manga: vec![], has_next_page: false })\n\
         }\n".to_string()
    };

    format!(
        r#"impl Guest for {struct_name} {{
    fn get_metadata() -> Result<ExtensionMetadata, wit_types::ExtensionError> {{
        Ok({struct_name}::metadata())
    }}

{popular_impl}
{search_impl}
    fn get_filter_list() -> Result<wit_types::FilterList, wit_types::ExtensionError> {{
        get_extension().get_filter_list().map_err(|e| e.into_wit())
    }}

    fn get_manga_details(manga_id: String) -> Result<MangaInfo, wit_types::ExtensionError> {{
        get_extension().get_manga_details(&manga_id).map_err(|e| e.into_wit())
    }}

    fn get_chapter_list(manga_id: String, page: i32, page_size: Option<i32>, sort: Option<String>) -> Result<ChapterList, wit_types::ExtensionError> {{
        get_extension().get_chapter_list(&manga_id, page, page_size, sort).map_err(|e| e.into_wit())
    }}

    fn get_chapter_sort_list() -> Result<Vec<wit_types::ChapterSortOption>, wit_types::ExtensionError> {{
        get_extension().get_chapter_sort_list().map_err(|e| e.into_wit())
    }}

    fn get_pages(manga_id: String, chapter_id: String) -> Result<Chapter, wit_types::ExtensionError> {{
        get_extension().get_pages(&manga_id, &chapter_id).map_err(|e| e.into_wit())
    }}

    fn get_preferences() -> Result<Vec<PreferenceSpec>, wit_types::ExtensionError> {{
        get_extension().get_preferences().map_err(|e| e.into_wit())
    }}

    fn get_url(manga_id: String) -> Result<String, wit_types::ExtensionError> {{
        get_extension().get_url(&manga_id).map_err(|e| e.into_wit())
    }}
}}

static EXTENSION: OnceLock<{struct_name}> = OnceLock::new();

fn get_extension() -> &'static {struct_name} {{
    EXTENSION.get_or_init({struct_name}::new)
}}

bindings::export!({struct_name});
"#
    )
}

pub fn to_pascal_case(s: &str) -> String {
    s.split(['-', '_'])
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut c = p.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect()
}
