[workspace]
resolver = "3"
members = ["kani-core", "kani-shared", "kani-extensions/*", "kani-web"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.wasm-release]
inherits = "release"
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"

[workspace.lints.clippy]
unwrap_used = { level = "deny", priority = 1 }
pedantic = "warn"
nursery = "warn"
