[package]
name = "kani-core"
version = "0.1.0"
edition = "2024"

[dependencies]
kani-shared = { path = "../kani-shared" }

# Async runtime
tokio = { version = "1.49.0", features = ["full"] }
futures = "0.3.31"

# HTTP client
rquest = { version = "5.1.0", features = ["json"] }
rquest-util = "2.2.1"

# WASM runtime
# WASM runtime
wasmtime = { version = "41.0.2", features = ["async", "component-model"] }
wit-bindgen = "0.53.1"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
quick-xml = { version = "0.39.2", features = ["serialize"] }

# HTML parsing (for extensions)
scraper = "0.25.0"

# Error handling
thiserror = "2.0.18"

# Archive handling
zip = { version = "7.2.0", default-features = false, features = ["deflate"] }
async_zip = { version = "0.0.18", features = ["tokio"] }

# Logging
tracing = "0.1.44"
bytes = "1.11.1"
chrono = "0.4.43"
arc-swap = "1.8.2"
ego-tree = "^0.10.0"
tokio-util = { version = "0.7.18", features = ["compat"] }
hickory-resolver = "0.25.2"
dashmap = "6.1.0"


[dev-dependencies]
tokio-test = "0.4"
