//! Host ABI function implementations for WASM extensions.
//!
//! This module implements the host-side functions that WASM extensions can call.
//! The ABI contract is defined by the `wit/kani.wit` file and generated by `bindgen!`.

use super::HostState;
use crate::wasm::kani::extension::{html, http, types, utility};

impl http::Host for HostState {
    async fn send(&mut self, req: http::Request) -> wasmtime::Result<http::Response, String> {
        let method = match req.method {
            http::Method::Get => rquest::Method::GET,
            http::Method::Post => rquest::Method::POST,
            http::Method::Put => rquest::Method::PUT,
            http::Method::Delete => rquest::Method::DELETE,
        };

        let url = match req.url.parse::<rquest::Url>() {
            Ok(u) => u,
            Err(e) => return Err(format!("Invalid URL: {}", e)),
        };

        let mut builder = self.http_client.inner().request(method, url);

        for (k, v) in req.headers {
            builder = builder.header(k, v);
        }

        if let Some(body) = req.body {
            builder = builder.body(body);
        }

        let request = match builder.build().map_err(|e| e.to_string()) {
            Ok(req) => req,
            Err(e) => return Err(e),
        };

        let response = match self.http_client.send_request(request).await {
            Ok(res) => res,
            Err(e) => return Err(e.to_string()),
        };

        let status = response.status().as_u16();
        let headers: Vec<(String, String)> = response
            .headers()
            .iter()
            .map(|(k, v)| (k.to_string(), v.to_str().unwrap_or("").to_string()))
            .collect();

        let body = match response.bytes().await.map_err(|e| e.to_string()) {
            Ok(b) => b.to_vec(),
            Err(e) => return Err(e),
        };

        Ok(http::Response {
            status,
            headers,
            body,
        })
    }
}

impl html::Host for HostState {
    fn parse(&mut self, html: String) -> wasmtime::Result<html::DocHandle, String> {
        let handle = self.next_doc_handle;
        self.next_doc_handle += 1;
        self.html_docs.insert(handle, html);
        Ok(handle)
    }

    fn select(
        &mut self,
        doc: html::DocHandle,
        selector: String,
    ) -> wasmtime::Result<html::ListHandle, String> {
        let doc_str = match self.html_docs.get(&doc) {
            Some(s) => s,
            None => return Err("Document not found".to_string()),
        };

        let selector_obj = match scraper::Selector::parse(&selector) {
            Ok(s) => s,
            Err(e) => return Err(format!("Invalid selector: {:?}", e)),
        };

        let fragment = scraper::Html::parse_fragment(doc_str);
        let matches: Vec<String> = fragment
            .root_element()
            .select(&selector_obj)
            .map(|e| e.html())
            .collect();

        let list_handle = self.next_doc_handle;
        self.next_doc_handle += 1;
        self.html_lists.insert(list_handle, matches);
        Ok(list_handle)
    }

    fn attr(
        &mut self,
        doc: html::DocHandle,
        selector: String,
        attr: String,
    ) -> wasmtime::Result<Option<String>, String> {
        let doc_str = match self.html_docs.get(&doc) {
            Some(s) => s,
            None => return Err("Document not found".to_string()),
        };
        let selector_obj = match scraper::Selector::parse(&selector) {
            Ok(s) => s,
            Err(_) => return Ok(None),
        };
        let fragment = scraper::Html::parse_fragment(doc_str);

        Ok(fragment
            .root_element()
            .select(&selector_obj)
            .next()
            .and_then(|el| el.value().attr(&attr).map(|s| s.to_string())))
    }

    fn text(
        &mut self,
        doc: html::DocHandle,
        selector: String,
    ) -> wasmtime::Result<Option<String>, String> {
        let doc_str = match self.html_docs.get(&doc) {
            Some(s) => s,
            None => return Err("Document not found".to_string()),
        };
        let selector_obj = match scraper::Selector::parse(&selector) {
            Ok(s) => s,
            Err(_) => return Ok(None),
        };
        let fragment = scraper::Html::parse_fragment(doc_str);

        Ok(fragment
            .root_element()
            .select(&selector_obj)
            .next()
            .map(|el| el.text().collect::<Vec<_>>().join("")))
    }

    fn drop_doc(&mut self, handle: html::DocHandle) {
        self.html_docs.remove(&handle);
    }

    fn drop_list(&mut self, handle: html::ListHandle) {
        self.html_lists.remove(&handle);
    }

    fn list_len(&mut self, handle: html::ListHandle) -> wasmtime::Result<i32, String> {
        Ok(self
            .html_lists
            .get(&handle)
            .map(|l| l.len() as i32)
            .unwrap_or(0))
    }

    fn list_get(
        &mut self,
        handle: html::ListHandle,
        index: i32,
    ) -> wasmtime::Result<html::DocHandle, String> {
        let list = match self.html_lists.get(&handle) {
            Some(l) => l,
            None => return Err("List not found".to_string()),
        };
        if index < 0 || index as usize >= list.len() {
            return Err("Index out of bounds".to_string());
        }

        let item = list[index as usize].clone();
        let doc_handle = self.next_doc_handle;
        self.next_doc_handle += 1;
        self.html_docs.insert(doc_handle, item);
        Ok(doc_handle)
    }

    fn inner_html(&mut self, doc: html::DocHandle) -> wasmtime::Result<Option<String>, String> {
        let doc_str = match self.html_docs.get(&doc) {
            Some(s) => s,
            None => return Err("Document not found".to_string()),
        };
        let fragment = scraper::Html::parse_fragment(doc_str);
        let res = fragment
            .root_element()
            .child_elements()
            .next()
            .map(|root| root.inner_html())
            .or_else(|| Some(doc_str.clone()));
        Ok(res)
    }

    fn outer_html(&mut self, doc: html::DocHandle) -> wasmtime::Result<Option<String>, String> {
        Ok(self.html_docs.get(&doc).cloned())
    }

    fn first(
        &mut self,
        doc: html::DocHandle,
        selector: String,
    ) -> wasmtime::Result<Option<html::DocHandle>, String> {
        let doc_str = match self.html_docs.get(&doc) {
            Some(s) => s,
            None => return Err("Document not found".to_string()),
        };
        let selector_obj = match scraper::Selector::parse(&selector) {
            Ok(s) => s,
            Err(_) => return Ok(None),
        };
        let fragment = scraper::Html::parse_fragment(doc_str);

        let first_html = match fragment.root_element().select(&selector_obj).next() {
            Some(el) => el.html(),
            None => return Ok(None),
        };

        let handle = self.next_doc_handle;
        self.next_doc_handle += 1;
        self.html_docs.insert(handle, first_html);
        Ok(Some(handle))
    }

    fn children(&mut self, doc: html::DocHandle) -> wasmtime::Result<html::ListHandle, String> {
        let doc_str = self.html_docs.get(&doc).cloned().unwrap_or_default();
        let fragment = scraper::Html::parse_fragment(&doc_str);

        let children: Vec<String> = fragment
            .root_element()
            .child_elements()
            .flat_map(|root| root.child_elements())
            .map(|el| el.html())
            .collect();

        let list_handle = self.next_doc_handle;
        self.next_doc_handle += 1;
        self.html_lists.insert(list_handle, children);
        Ok(list_handle)
    }
}

impl utility::Host for HostState {
    fn date_parse(&mut self, date: String, fmt: String) -> wasmtime::Result<i64, String> {
        chrono::NaiveDateTime::parse_from_str(&date, &fmt)
            .map(|dt| dt.and_utc().timestamp())
            .map_err(|_| "Unable to parse date".to_string())
    }
}

impl types::Host for HostState {}
