//! Host ABI function implementations for WASM extensions.
//!
//! This module implements the host-side functions that WASM extensions can call.
//! The ABI contract is defined by the `wit/kani.wit` file and generated by `bindgen!`.

use super::{HostState, SafeHtml, SendHtml, StoredNode};
use crate::wasm::kani::extension::{html, http, json, types, utility};
use std::sync::{Arc, Mutex};

const MAX_HTTP_RESPONSE_BYTES: usize = 5 * 1024 * 1024; // 5 MB

impl http::Host for HostState {
    #[tracing::instrument(skip(self, req), fields(method = ?req.method, url = %req.url))]
    async fn send(&mut self, req: http::Request) -> wasmtime::Result<http::Response, String> {
        let method = match req.method {
            http::Method::Get => rquest::Method::GET,
            http::Method::Post => rquest::Method::POST,
            http::Method::Put => rquest::Method::PUT,
            http::Method::Delete => rquest::Method::DELETE,
        };

        let url = match req.url.parse::<rquest::Url>() {
            Ok(u) => u,
            Err(e) => return Err(format!("Invalid URL: {}", e)),
        };

        if let Some(allowed) = &self.allowed_host {
            let req_host = url.host_str().unwrap_or("");
            if req_host != allowed {
                return Err(format!(
                    "Request blocked: extension may only contact '{}', got '{}'",
                    allowed, req_host
                ));
            }
        }

        let mut builder = self.http_client.inner().request(method, url);

        for (k, v) in req.headers {
            builder = builder.header(k, v);
        }

        if let Some(body) = req.body {
            builder = builder.body(body);
        }

        let request = builder.build().map_err(|e| e.to_string())?;

        let ttfb_start = std::time::Instant::now();
        let response = self
            .http_client
            .send_request(request)
            .await
            .map_err(|e| e.to_string())?;

        let ttfb = ttfb_start.elapsed();
        let status = response.status().as_u16();

        tracing::info!(
            ttfb_ms = ttfb.as_millis(),
            status_code = status,
            "Connection established and headers received"
        );
        let headers: Vec<(String, String)> = response
            .headers()
            .iter()
            .map(|(k, v)| (k.to_string(), v.to_str().unwrap_or("").to_string()))
            .collect();

        let body = response
            .bytes_limited(MAX_HTTP_RESPONSE_BYTES)
            .await
            .map_err(|e| e.to_string())?
            .to_vec();

        Ok(http::Response {
            status,
            headers,
            body,
        })
    }
}

impl html::Host for HostState {
    fn parse(&mut self, html: String) -> wasmtime::Result<html::DocHandle, String> {
        let parsed_doc = SafeHtml::parse_document(&html);

        let handle = self.next_doc_handle;
        let root_id = parsed_doc.0.root_element().id();
        let parsed = SendHtml(Arc::new(Mutex::new(parsed_doc)));

        self.next_doc_handle += 1;

        self.html_docs.insert(
            handle,
            StoredNode {
                doc: parsed.0,
                node_id: root_id,
            },
        );

        Ok(handle)
    }

    fn select(
        &mut self,
        doc: html::DocHandle,
        selector: String,
    ) -> wasmtime::Result<html::ListHandle, String> {
        let doc = match self.html_docs.get(&doc) {
            Some(s) => s.clone(),
            None => return Err("Document not found".to_string()),
        };

        let selector_obj = self.get_or_parse_selector(&selector)?;

        let doc_lock = doc.doc.lock().unwrap();
        let element = match scraper::ElementRef::wrap(doc_lock.0.tree.get(doc.node_id).unwrap()) {
            Some(el) => el,
            None => return Err("Root node is not an element".to_string()),
        };

        let matches: Vec<StoredNode> = element
            .select(selector_obj)
            .map(|e| StoredNode {
                doc: doc.doc.clone(),
                node_id: e.id(),
            })
            .collect();

        let list_handle = self.next_doc_handle;
        self.next_doc_handle += 1;
        self.html_lists.insert(list_handle, matches);
        Ok(list_handle)
    }

    fn attr(
        &mut self,
        doc: html::DocHandle,
        selector: String,
        attr: String,
    ) -> wasmtime::Result<Option<String>, String> {
        let doc = match self.html_docs.get(&doc) {
            Some(s) => s.clone(),
            None => return Err("Document not found".to_string()),
        };

        let doc_lock = doc.doc.lock().unwrap();
        let element = match scraper::ElementRef::wrap(doc_lock.0.tree.get(doc.node_id).unwrap()) {
            Some(el) => el,
            None => return Ok(None),
        };

        if selector.is_empty() {
            return Ok(element.value().attr(&attr).map(|s| s.to_string()));
        }

        let selector_obj = match self.get_or_parse_selector(&selector) {
            Ok(s) => s,
            Err(_) => return Ok(None),
        };

        Ok(element
            .select(selector_obj)
            .next()
            .and_then(|el| el.value().attr(&attr).map(|s| s.to_string())))
    }

    fn text(
        &mut self,
        doc: html::DocHandle,
        selector: String,
    ) -> wasmtime::Result<Option<String>, String> {
        let doc = match self.html_docs.get(&doc) {
            Some(s) => s.clone(),
            None => return Err("Document not found".to_string()),
        };

        let doc_lock = doc.doc.lock().unwrap();
        let element = match scraper::ElementRef::wrap(doc_lock.0.tree.get(doc.node_id).unwrap()) {
            Some(el) => el,
            None => return Ok(None),
        };

        if selector.is_empty() {
            return Ok(Some(element.text().collect::<Vec<_>>().join("")));
        }

        let selector_obj = match self.get_or_parse_selector(&selector) {
            Ok(s) => s,
            Err(_) => return Ok(None),
        };

        Ok(element
            .select(selector_obj)
            .next()
            .map(|el| el.text().collect::<Vec<_>>().join("")))
    }

    fn drop_doc(&mut self, handle: html::DocHandle) {
        self.html_docs.remove(&handle);
    }

    fn drop_list(&mut self, handle: html::ListHandle) {
        self.html_lists.remove(&handle);
    }

    fn list_len(&mut self, handle: html::ListHandle) -> wasmtime::Result<i32, String> {
        Ok(self
            .html_lists
            .get(&handle)
            .map(|l| l.len() as i32)
            .unwrap_or(0))
    }

    fn list_get(
        &mut self,
        handle: html::ListHandle,
        index: i32,
    ) -> wasmtime::Result<html::DocHandle, String> {
        let list = match self.html_lists.get(&handle) {
            Some(l) => l,
            None => return Err("List not found".to_string()),
        };
        if index < 0 || index as usize >= list.len() {
            return Err("Index out of bounds".to_string());
        }

        let item_node = list[index as usize].clone();
        let doc_handle = self.next_doc_handle;
        self.next_doc_handle += 1;
        self.html_docs.insert(doc_handle, item_node);
        Ok(doc_handle)
    }

    fn inner_html(&mut self, doc: html::DocHandle) -> wasmtime::Result<Option<String>, String> {
        let doc = match self.html_docs.get(&doc) {
            Some(s) => s,
            None => return Err("Document not found".to_string()),
        };

        let doc_lock = doc.doc.lock().unwrap();
        let element = match scraper::ElementRef::wrap(doc_lock.0.tree.get(doc.node_id).unwrap()) {
            Some(el) => el,
            None => return Ok(None),
        };

        Ok(Some(element.inner_html()))
    }

    fn outer_html(&mut self, doc: html::DocHandle) -> wasmtime::Result<Option<String>, String> {
        let doc = match self.html_docs.get(&doc) {
            Some(s) => s,
            None => return Err("Document not found".to_string()),
        };

        let doc_lock = doc.doc.lock().unwrap();
        let element = match scraper::ElementRef::wrap(doc_lock.0.tree.get(doc.node_id).unwrap()) {
            Some(el) => el,
            None => return Ok(None),
        };

        Ok(Some(element.html()))
    }

    fn first(
        &mut self,
        doc: html::DocHandle,
        selector: String,
    ) -> wasmtime::Result<Option<html::DocHandle>, String> {
        let doc = match self.html_docs.get(&doc) {
            Some(s) => s.clone(),
            None => return Err("Document not found".to_string()),
        };
        let selector_obj = match self.get_or_parse_selector(&selector) {
            Ok(s) => s,
            Err(_) => return Ok(None),
        };

        let doc_lock = doc.doc.lock().unwrap();
        let element = match scraper::ElementRef::wrap(doc_lock.0.tree.get(doc.node_id).unwrap()) {
            Some(el) => el,
            None => return Ok(None),
        };

        let matched = match element.select(selector_obj).next() {
            Some(el) => el.id(),
            None => return Ok(None),
        };

        let handle = self.next_doc_handle;
        self.next_doc_handle += 1;
        self.html_docs.insert(
            handle,
            StoredNode {
                doc: doc.doc.clone(),
                node_id: matched,
            },
        );
        Ok(Some(handle))
    }

    fn children(&mut self, doc: html::DocHandle) -> wasmtime::Result<html::ListHandle, String> {
        let doc = match self.html_docs.get(&doc) {
            Some(s) => s,
            None => return Err("Document not found".to_string()),
        };

        let doc_lock = doc.doc.lock().unwrap();
        let element = match scraper::ElementRef::wrap(doc_lock.0.tree.get(doc.node_id).unwrap()) {
            Some(el) => el,
            None => return Err("Root node is not an element".to_string()),
        };

        let children: Vec<StoredNode> = element
            .children()
            .filter_map(scraper::ElementRef::wrap)
            .map(|el| StoredNode {
                doc: doc.doc.clone(),
                node_id: el.id(),
            })
            .collect();

        let list_handle = self.next_doc_handle;
        self.next_doc_handle += 1;
        self.html_lists.insert(list_handle, children);
        Ok(list_handle)
    }
}

impl utility::Host for HostState {
    fn date_parse(&mut self, date: String, fmt: String) -> wasmtime::Result<i64, String> {
        chrono::NaiveDateTime::parse_from_str(&date, &fmt)
            .map(|dt| dt.and_utc().timestamp())
            .map_err(|_| "Unable to parse date".to_string())
    }
}

impl json::Host for HostState {
    fn parse(&mut self, data: Vec<u8>) -> wasmtime::Result<i32, String> {
        let value: serde_json::Value =
            serde_json::from_slice(&data).map_err(|e| format!("JSON parse error: {}", e))?;

        let handle = self.next_doc_handle;
        self.next_doc_handle += 1;
        self.json_docs.insert(handle, value);

        Ok(handle)
    }

    fn get_str(&mut self, handle: i32, ptr: String) -> wasmtime::Result<Option<String>, String> {
        let value = self
            .json_docs
            .get(&handle)
            .ok_or_else(|| "Invalid JSON handle".to_string())?;

        Ok(value
            .pointer(&ptr)
            .and_then(|v| v.as_str())
            .map(|s| s.to_string()))
    }

    fn get_i64(&mut self, handle: i32, ptr: String) -> wasmtime::Result<Option<i64>, String> {
        let value = self
            .json_docs
            .get(&handle)
            .ok_or_else(|| "Invalid JSON handle".to_string())?;

        Ok(value.pointer(&ptr).and_then(|v| v.as_i64()))
    }

    fn get_f64(&mut self, handle: i32, ptr: String) -> wasmtime::Result<Option<f64>, String> {
        let value = self
            .json_docs
            .get(&handle)
            .ok_or_else(|| "Invalid JSON handle".to_string())?;

        Ok(value.pointer(&ptr).and_then(|v| v.as_f64()))
    }

    fn get_bool(&mut self, handle: i32, ptr: String) -> wasmtime::Result<Option<bool>, String> {
        let value = self
            .json_docs
            .get(&handle)
            .ok_or_else(|| "Invalid JSON handle".to_string())?;

        Ok(value.pointer(&ptr).and_then(|v| v.as_bool()))
    }

    fn array_len(&mut self, handle: i32, ptr: String) -> wasmtime::Result<Option<i32>, String> {
        let value = self
            .json_docs
            .get(&handle)
            .ok_or_else(|| "Invalid JSON handle".to_string())?;

        Ok(value
            .pointer(&ptr)
            .and_then(|v| v.as_array())
            .map(|a| a.len() as i32))
    }

    fn array_get(&mut self, handle: i32, ptr: String, index: i32) -> wasmtime::Result<i32, String> {
        let value = self
            .json_docs
            .get(&handle)
            .ok_or_else(|| "Invalid JSON handle".to_string())?;

        let element = value
            .pointer(&ptr)
            .and_then(|v| v.as_array())
            .and_then(|a| a.get(index as usize))
            .ok_or_else(|| format!("No element at {}[{}]", ptr, index))?
            .clone();

        let child_handle = self.next_doc_handle;
        self.next_doc_handle += 1;
        self.json_docs.insert(child_handle, element);

        Ok(child_handle)
    }

    fn drop_json(&mut self, handle: i32) {
        self.json_docs.remove(&handle);
    }
}

impl types::Host for HostState {}
