//! Host ABI function implementations for WASM extensions.
//!
//! This module implements the host-side functions that WASM extensions can call.
//! The ABI contract is defined by the `wit/kani.wit` file and generated by `bindgen!`.

use super::{HostState, SendHtml, StoredNode};
use crate::evaluator::html_eval::{extract_html, extract_html_paginated};
use crate::evaluator::json_eval::{extract_json, extract_json_paginated};
use crate::utilities::parse_date_flexible;
use crate::wasm::kani::extension::{
    cache, extraction, html, http, json, prefs, scripting, types, utility,
};

use postcard;

const MAX_HTTP_RESPONSE_BYTES: usize = 15 * 1024 * 1024; // 15 MB

fn decode_blueprint(bytes: &[u8]) -> Result<kani_shared::ast::Blueprint, String> {
    let (version, rest) = postcard::take_from_bytes::<u32>(bytes)
        .map_err(|e| format!("Invalid blueprint header: {}", e))?;
    if version != kani_shared::ast::DSL_SCHEMA_VERSION {
        return Err(format!(
            "Blueprint DSL schema version {} is not supported (host requires {}); recompile the extension",
            version,
            kani_shared::ast::DSL_SCHEMA_VERSION,
        ));
    }
    postcard::from_bytes(rest).map_err(|e| format!("Invalid blueprint: {}", e))
}

impl http::Host for HostState {
    #[tracing::instrument(level = "debug", skip(self, req), fields(method = ?req.method, url = %req.url))]
    async fn send(&mut self, req: http::Request) -> wasmtime::Result<http::Response, String> {
        self.charge_io()?;

        let method = match req.method {
            http::Method::Get => rquest::Method::GET,
            http::Method::Post => rquest::Method::POST,
            http::Method::Put => rquest::Method::PUT,
            http::Method::Delete => rquest::Method::DELETE,
        };

        let url = req
            .url
            .parse::<rquest::Url>()
            .map_err(|e| format!("Invalid URL: {}", e))?;

        self.check_allowed_host(url.host_str().unwrap_or(""))?;

        let mut builder = self.http_client.inner().request(method, url);
        for (k, v) in req.headers {
            builder = builder.header(k, v);
        }
        if let Some(body) = req.body {
            builder = builder.body(body);
        }
        let request = builder.build().map_err(|e| e.to_string())?;

        let ttfb_start = std::time::Instant::now();
        let response = tokio::time::timeout(
            std::time::Duration::from_secs(90),
            self.http_client.send_request(request),
        )
        .await
        .map_err(|_| "HTTP request timed out after 90 seconds".to_string())?
        .map_err(|e| e.to_string())?;
        let ttfb = ttfb_start.elapsed();
        self.last_io_at = Some(std::time::Instant::now());

        let status = response.status().as_u16();
        if crate::HTTP_LOGGING_ENABLED.load(std::sync::atomic::Ordering::Relaxed) {
            tracing::info!(
                ttfb_ms = ttfb.as_millis(),
                status_code = status,
                "Connection established and headers received"
            );
        }
        let headers = response
            .headers()
            .iter()
            .map(|(k, v)| (k.to_string(), v.to_str().unwrap_or("").to_string()))
            .collect();
        let body = response
            .bytes_limited(MAX_HTTP_RESPONSE_BYTES)
            .await
            .map_err(|e| e.to_string())?
            .to_vec();
        Ok(http::Response {
            status,
            headers,
            body,
        })
    }
}

impl html::Host for HostState {
    fn parse(&mut self, html: String) -> wasmtime::Result<html::DocHandle, String> {
        self.check_handle_capacity()?;
        let parsed = SendHtml::parse_document(&html);
        let root_id = parsed
            .0
            .lock()
            .unwrap_or_else(|e| e.into_inner())
            .0
            .root_element()
            .id();
        let handle = self.next_doc_handle;
        self.next_doc_handle += 1;
        self.html_docs.insert(
            handle,
            StoredNode {
                doc: parsed.0,
                node_id: root_id,
            },
        );
        Ok(handle)
    }

    fn select(
        &mut self,
        doc: html::DocHandle,
        selector: String,
    ) -> wasmtime::Result<html::ListHandle, String> {
        let doc = self.get_html_doc(doc)?.clone();
        let sel = self.get_or_parse_selector(&selector)?;
        let matches = doc.with_element(|el| {
            Ok(el
                .select(sel)
                .map(|e| StoredNode {
                    doc: doc.doc.clone(),
                    node_id: e.id(),
                })
                .collect())
        })?;
        self.check_handle_capacity()?;
        let handle = self.next_doc_handle;
        self.next_doc_handle += 1;
        self.html_lists.insert(handle, matches);
        Ok(handle)
    }

    fn attr(
        &mut self,
        doc: html::DocHandle,
        selector: String,
        attr: String,
    ) -> wasmtime::Result<Option<String>, String> {
        let doc = self.get_html_doc(doc)?.clone();
        if selector.is_empty() {
            return doc.try_with_element(|el| Ok(el.value().attr(&attr).map(|s| s.to_string())));
        }
        let sel = match self.get_or_parse_selector(&selector) {
            Ok(s) => s,
            Err(_) => return Ok(None),
        };
        doc.try_with_element(|el| {
            Ok(el
                .select(sel)
                .next()
                .and_then(|el| el.value().attr(&attr).map(|s| s.to_string())))
        })
    }

    fn text(
        &mut self,
        doc: html::DocHandle,
        selector: String,
    ) -> wasmtime::Result<Option<String>, String> {
        let doc = self.get_html_doc(doc)?.clone();
        if selector.is_empty() {
            return doc.try_with_element(|el| Ok(Some(el.text().collect::<String>())));
        }
        let sel = match self.get_or_parse_selector(&selector) {
            Ok(s) => s,
            Err(_) => return Ok(None),
        };
        doc.try_with_element(|el| {
            Ok(el
                .select(sel)
                .next()
                .map(|el| el.text().collect::<String>()))
        })
    }

    fn drop_doc(&mut self, handle: html::DocHandle) {
        self.html_docs.remove(&handle);
    }
    fn drop_list(&mut self, handle: html::ListHandle) {
        self.html_lists.remove(&handle);
    }

    fn list_len(&mut self, handle: html::ListHandle) -> wasmtime::Result<i32, String> {
        Ok(self
            .html_lists
            .get(&handle)
            .map(|l| l.len() as i32)
            .unwrap_or(0))
    }

    fn list_get(
        &mut self,
        handle: html::ListHandle,
        index: i32,
    ) -> wasmtime::Result<html::DocHandle, String> {
        let list = self.html_lists.get(&handle).ok_or("List not found")?;
        if index < 0 || index as usize >= list.len() {
            return Err("Index out of bounds".to_string());
        }
        let item_node = list[index as usize].clone();
        self.check_handle_capacity()?;
        let doc_handle = self.next_doc_handle;
        self.next_doc_handle += 1;
        self.html_docs.insert(doc_handle, item_node);
        Ok(doc_handle)
    }

    fn inner_html(&mut self, doc: html::DocHandle) -> wasmtime::Result<Option<String>, String> {
        self.get_html_doc(doc)?
            .try_with_element(|el| Ok(Some(el.inner_html())))
    }

    fn outer_html(&mut self, doc: html::DocHandle) -> wasmtime::Result<Option<String>, String> {
        self.get_html_doc(doc)?
            .try_with_element(|el| Ok(Some(el.html())))
    }

    fn first(
        &mut self,
        doc: html::DocHandle,
        selector: String,
    ) -> wasmtime::Result<Option<html::DocHandle>, String> {
        let doc = self.get_html_doc(doc)?.clone();
        let sel = match self.get_or_parse_selector(&selector) {
            Ok(s) => s,
            Err(_) => return Ok(None),
        };
        let matched_id =
            match doc.try_with_element(|el| Ok(el.select(sel).next().map(|e| e.id())))? {
                Some(id) => id,
                None => return Ok(None),
            };
        self.check_handle_capacity()?;
        let handle = self.next_doc_handle;
        self.next_doc_handle += 1;
        self.html_docs.insert(
            handle,
            StoredNode {
                doc: doc.doc,
                node_id: matched_id,
            },
        );
        Ok(Some(handle))
    }

    fn children(&mut self, doc: html::DocHandle) -> wasmtime::Result<html::ListHandle, String> {
        let doc = self.get_html_doc(doc)?.clone();
        let children = doc.with_element(|el| {
            Ok(el
                .children()
                .filter_map(scraper::ElementRef::wrap)
                .map(|el| StoredNode {
                    doc: doc.doc.clone(),
                    node_id: el.id(),
                })
                .collect())
        })?;
        self.check_handle_capacity()?;
        let handle = self.next_doc_handle;
        self.next_doc_handle += 1;
        self.html_lists.insert(handle, children);
        Ok(handle)
    }
}

impl utility::Host for HostState {
    fn date_parse(&mut self, date: String, fmt: String) -> wasmtime::Result<i64, String> {
        parse_date_flexible(&date, &fmt)
    }

    fn date_parse_rfc3339(&mut self, date: String) -> wasmtime::Result<i64, String> {
        time::OffsetDateTime::parse(&date, &time::format_description::well_known::Rfc3339)
            .map(|dt| dt.unix_timestamp())
            .map_err(|e| format!("Invalid RFC3339 date string: {}", e))
    }

    fn resolve_url(&mut self, base: String, path: String) -> Result<String, String> {
        url::Url::parse(&base)
            .map_err(|e| e.to_string())?
            .join(&path)
            .map(|u| u.to_string())
            .map_err(|e| e.to_string())
    }

    fn build_url(
        &mut self,
        base: String,
        queries: Vec<(String, String)>,
    ) -> Result<String, String> {
        let mut url = url::Url::parse(&base).map_err(|e| format!("Invalid base URL: {}", e))?;
        url.query_pairs_mut().extend_pairs(queries.iter());
        Ok(url.to_string())
    }

    fn url_encode(&mut self, input: String) -> String {
        urlencoding::encode(&input).into_owned()
    }

    fn url_decode(&mut self, input: String) -> Result<String, String> {
        urlencoding::decode(&input)
            .map(|c| c.into_owned())
            .map_err(|e| format!("Failed to decode URL string: {}", e))
    }

    fn get_query_param(&mut self, url: String, key: String) -> Option<String> {
        url::Url::parse(&url)
            .ok()?
            .query_pairs()
            .find(|(k, _)| k == &key)
            .map(|(_, v)| v.into_owned())
    }

    fn encode_form(&mut self, data: Vec<(String, String)>) -> String {
        url::form_urlencoded::Serializer::new(String::new())
            .extend_pairs(data)
            .finish()
    }

    fn log(&mut self, level: u8, line: u32, message: String) {
        match level {
            0 => tracing::debug!(target: "ext", line = %line, "{}", message),
            1 => tracing::info!(target:  "ext", line = %line, "{}", message),
            2 => tracing::warn!(target:  "ext", line = %line, "{}", message),
            _ => tracing::error!(target: "ext", line = %line, "{}", message),
        }
    }
}

impl json::Host for HostState {
    fn parse(&mut self, data: Vec<u8>) -> wasmtime::Result<i32, String> {
        self.check_handle_capacity()?;
        let value: serde_json::Value =
            serde_json::from_slice(&data).map_err(|e| format!("JSON parse error: {}", e))?;
        let handle = self.next_doc_handle;
        self.next_doc_handle += 1;
        self.json_docs.insert(handle, value);
        Ok(handle)
    }

    fn get_str(&mut self, handle: i32, ptr: String) -> wasmtime::Result<Option<String>, String> {
        Ok(self
            .get_json(handle)?
            .pointer(&ptr)
            .and_then(|v| v.as_str())
            .map(|s| s.to_string()))
    }

    fn get_i64(&mut self, handle: i32, ptr: String) -> wasmtime::Result<Option<i64>, String> {
        Ok(self
            .get_json(handle)?
            .pointer(&ptr)
            .and_then(|v| v.as_i64()))
    }

    fn get_f64(&mut self, handle: i32, ptr: String) -> wasmtime::Result<Option<f64>, String> {
        Ok(self
            .get_json(handle)?
            .pointer(&ptr)
            .and_then(|v| v.as_f64()))
    }

    fn get_bool(&mut self, handle: i32, ptr: String) -> wasmtime::Result<Option<bool>, String> {
        Ok(self
            .get_json(handle)?
            .pointer(&ptr)
            .and_then(|v| v.as_bool()))
    }

    fn array_len(&mut self, handle: i32, ptr: String) -> wasmtime::Result<Option<i32>, String> {
        Ok(self
            .get_json(handle)?
            .pointer(&ptr)
            .and_then(|v| v.as_array())
            .map(|a| a.len() as i32))
    }

    fn array_get(&mut self, handle: i32, ptr: String, index: i32) -> wasmtime::Result<i32, String> {
        let element = self
            .get_json(handle)?
            .pointer(&ptr)
            .and_then(|v| v.as_array())
            .and_then(|a| a.get(index as usize))
            .ok_or_else(|| format!("No element at {}[{}]", ptr, index))?
            .clone();
        self.check_handle_capacity()?;
        let child_handle = self.next_doc_handle;
        self.next_doc_handle += 1;
        self.json_docs.insert(child_handle, element);
        Ok(child_handle)
    }

    fn object_keys(&mut self, handle: i32, ptr: String) -> wasmtime::Result<Vec<String>, String> {
        let value = self.get_json(handle)?;
        let target = if ptr.is_empty() {
            value
        } else {
            value
                .pointer(&ptr)
                .ok_or_else(|| format!("No value at pointer '{}'", ptr))?
        };
        target
            .as_object()
            .map(|obj| obj.keys().cloned().collect())
            .ok_or_else(|| format!("Value at '{}' is not an object", ptr))
    }

    fn object_get(
        &mut self,
        handle: i32,
        ptr: String,
        key: String,
    ) -> wasmtime::Result<Option<i32>, String> {
        let value = self.get_json(handle)?;
        let target = if ptr.is_empty() {
            value
        } else {
            value
                .pointer(&ptr)
                .ok_or_else(|| format!("No value at pointer '{}'", ptr))?
        };
        match target.as_object().and_then(|obj| obj.get(&key)) {
            Some(child) => {
                let child = child.clone();
                self.check_handle_capacity()?;
                let child_handle = self.next_doc_handle;
                self.next_doc_handle += 1;
                self.json_docs.insert(child_handle, child);
                Ok(Some(child_handle))
            }
            None => Ok(None),
        }
    }

    fn to_string(&mut self, handle: i32) -> wasmtime::Result<String, String> {
        serde_json::to_string(self.get_json(handle)?)
            .map_err(|e| format!("JSON serialization error: {}", e))
    }

    fn drop_json(&mut self, handle: i32) {
        self.json_docs.remove(&handle);
    }
}

impl prefs::Host for HostState {
    fn get_value(&mut self, key: String) -> Option<String> {
        self.preferences.get(&key).cloned()
    }
}

impl types::Host for HostState {}

impl extraction::Host for HostState {
    async fn extract_html(
        &mut self,
        doc: Option<i32>,
        blueprint: Vec<u8>,
    ) -> wasmtime::Result<i32, String> {
        let bp = decode_blueprint(&blueprint)?;
        let value = extract_html(self, doc, &bp).await?;
        self.check_handle_capacity()?;
        let handle = self.next_doc_handle;
        self.next_doc_handle += 1;
        self.json_docs.insert(handle, value);
        Ok(handle)
    }

    async fn paginated_extract_html(
        &mut self,
        page: i32,
        page_size: i32,
        blueprint: Vec<u8>,
    ) -> wasmtime::Result<i32, String> {
        let bp = decode_blueprint(&blueprint)?;
        let value = extract_html_paginated(self, page, page_size, &bp).await?;
        self.check_handle_capacity()?;
        let handle = self.next_doc_handle;
        self.next_doc_handle += 1;
        self.json_docs.insert(handle, value);
        Ok(handle)
    }

    async fn extract_json(
        &mut self,
        doc: Option<i32>,
        blueprint: Vec<u8>,
    ) -> wasmtime::Result<i32, String> {
        let bp = decode_blueprint(&blueprint)?;
        let value = extract_json(self, doc, &bp).await?;
        self.check_handle_capacity()?;
        let handle = self.next_doc_handle;
        self.next_doc_handle += 1;
        self.json_docs.insert(handle, value);
        Ok(handle)
    }

    async fn paginated_extract_html_raw(
        &mut self,
        page: i32,
        page_size: i32,
        url: String,
        method: String,
        headers: Vec<(String, String)>,
        queries: Vec<(String, String)>,
        blueprint: Vec<u8>,
    ) -> wasmtime::Result<i32, String> {
        let mut bp = decode_blueprint(&blueprint)?;
        bp.request = Some(kani_shared::ast::RequestDef {
            url,
            method,
            headers,
            queries,
            endpoint_id: None,
        });
        let value = extract_html_paginated(self, page, page_size, &bp).await?;
        self.check_handle_capacity()?;
        let handle = self.next_doc_handle;
        self.next_doc_handle += 1;
        self.json_docs.insert(handle, value);
        Ok(handle)
    }

    async fn paginated_extract_json(
        &mut self,
        page: i32,
        page_size: i32,
        blueprint: Vec<u8>,
    ) -> wasmtime::Result<i32, String> {
        let bp = decode_blueprint(&blueprint)?;
        let value = extract_json_paginated(self, page, page_size, &bp).await?;
        self.check_handle_capacity()?;
        let handle = self.next_doc_handle;
        self.next_doc_handle += 1;
        self.json_docs.insert(handle, value);
        Ok(handle)
    }

    async fn paginated_extract_json_raw(
        &mut self,
        page: i32,
        page_size: i32,
        url: String,
        method: String,
        headers: Vec<(String, String)>,
        queries: Vec<(String, String)>,
        blueprint: Vec<u8>,
    ) -> wasmtime::Result<i32, String> {
        let mut bp = decode_blueprint(&blueprint)?;
        bp.request = Some(kani_shared::ast::RequestDef {
            url,
            method,
            headers,
            queries,
            endpoint_id: None,
        });
        let value = extract_json_paginated(self, page, page_size, &bp).await?;
        self.check_handle_capacity()?;
        let handle = self.next_doc_handle;
        self.next_doc_handle += 1;
        self.json_docs.insert(handle, value);
        Ok(handle)
    }
}

impl scripting::Host for HostState {
    async fn v8_context_exists(&mut self, name: String) -> bool {
        crate::v8_process::v8_context_exists(&self.v8_process, &name).await
    }

    async fn v8_context_create(&mut self, name: String, init_script: String) -> Result<(), String> {
        crate::v8_process::v8_context_create(&self.v8_process, &name, &init_script).await
    }

    async fn v8_context_eval(&mut self, name: String, script: String) -> Result<String, String> {
        crate::v8_process::v8_context_eval(&self.v8_process, &name, &script).await
    }

    async fn v8_context_drop(&mut self, name: String) {
        crate::v8_process::v8_context_drop(&self.v8_process, &name).await;
    }

    async fn capture_url_param(
        &mut self,
        page_url: String,
        opts: scripting::CaptureUrlParamOpts,
    ) -> Result<String, String> {
        self.charge_io()?;
        let result = crate::v8_process::capture_url_param(
            &self.v8_process,
            &page_url,
            &crate::v8_process::CaptureUrlParamOpts {
                url_pattern: &opts.url_pattern,
                param_name: opts.param_name.as_deref(),
                header_name: opts.header_name.as_deref(),
                timeout_ms: opts.timeout_ms,
                force_refresh: opts.force_refresh,
                cache_ttl_ms: opts.cache_ttl_ms,
                extra_headers: &opts.extra_headers,
            },
        )
        .await;
        // Reset the epoch deadline reference point so the post-browser-wait WASM
        // code doesn't immediately trip the "no recent IO" deadline check.
        self.last_io_at = Some(std::time::Instant::now());
        result
    }

    async fn capture_page_payload(
        &mut self,
        page_url: String,
        init_script: String,
        timeout_ms: u32,
    ) -> Result<String, String> {
        self.charge_io()?;
        let result = crate::v8_process::capture_page_payload(
            &self.v8_process,
            &page_url,
            &init_script,
            timeout_ms,
        )
        .await;
        self.last_io_at = Some(std::time::Instant::now());
        result
    }
}

impl cache::Host for HostState {
    async fn get(&mut self, key: String) -> Option<Vec<u8>> {
        let ns = self.ext_cache_namespace.clone();
        let backend = std::sync::Arc::clone(&self.ext_cache);
        backend.get(&ns, &key).await
    }

    async fn put(&mut self, key: String, value: Vec<u8>, ttl_secs: u32) {
        let ns = self.ext_cache_namespace.clone();
        let backend = std::sync::Arc::clone(&self.ext_cache);
        backend
            .put(
                &ns,
                &key,
                value,
                std::time::Duration::from_secs(u64::from(ttl_secs)),
            )
            .await;
    }

    async fn delete(&mut self, key: String) {
        let ns = self.ext_cache_namespace.clone();
        let backend = std::sync::Arc::clone(&self.ext_cache);
        backend.delete(&ns, &key).await;
    }

    async fn clear(&mut self) {
        let ns = self.ext_cache_namespace.clone();
        let backend = std::sync::Arc::clone(&self.ext_cache);
        backend.clear_namespace(&ns).await;
    }
}
