use crate::error::CliError;
use std::path::Path;

pub fn run(name: &str, rust: bool) -> Result<(), CliError> {
    let id = name.replace(' ', "-").to_lowercase();
    let struct_name = id
        .split('-')
        .map(|p| {
            let mut c = p.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect::<String>();

    if rust {
        return scaffold_rust(name, &id, &struct_name);
    }

    let filename = format!("{name}.yaml");
    let path = Path::new(&filename);

    if path.exists() {
        return Err(CliError::Other(format!("{filename} already exists")));
    }

    let content = format!(
        r#"# Kani declarative extension: {struct_name}
# Generated by `kani-cli new {name}` — fill in the TODOs and run `kani-cli validate {filename}`.

id: {id}
name: {struct_name}
version: "0.1.0"
base_url: "https://TODO.example.com"
language: en
nsfw: false
unrestricted_http: false

endpoints:
  popular:
    delegate_to: search
    empty_without_filters: false

  search:
    route: "/TODO/search"
    queries:
      q: $query$
    pagination:
      native_page_size: 20
      offset_param: "page"
      offset_type: page
      page_start: 1
    container: "TODO"
    fields:
      id: 'self.attr("href").split("/").at(-1)'
      title: 'self.first("h2").text()'
      cover_url:
        expr: 'self.first("img").attr("src")'
        optional: true

  manga_details:
    route: "/TODO/$manga_id$"
    container: ":root"
    fields:
      id: '"$manga_id$"'
      title: 'dom("h1").text()'
      status: 'dom(".status").text().lower().lookup({{"ongoing": "ongoing", "completed": "completed"}}).fallback("unknown")'
      cover_url:
        expr: 'dom("img.cover").attr("src")'
        optional: true
      description:
        expr: 'dom(".description").text()'
        optional: true
      authors: '["Unknown"]'
      artists: '["Unknown"]'
      tags:
        expr: 'self.select(".tag").map($item.text().trim())'
        optional: true

  chapter_list:
    route: "/TODO/$manga_id$"
    container: "TODO"
    has_next_page: false
    fields:
      id: 'self.attr("href").split("/").at(-1)'
      number: 'self.text().trim().parse_float().fallback(0.0)'
      title:
        expr: "null"
        optional: true
      volume:
        expr: "null"
        optional: true
      scanlator:
        expr: "null"
        optional: true
      date_uploaded:
        expr: "null"
        optional: true
      language: '"en"'

  pages:
    route: "/TODO/$chapter_id$"
    container: "img"
    fields:
      index: "index()"
      url: 'self.attr("src")'

filters: []
preferences: []
"#
    );

    std::fs::write(path, content)?;
    println!("Created {filename} — edit it and run `kani-cli validate {filename}`");
    Ok(())
}

fn scaffold_rust(name: &str, id: &str, struct_name: &str) -> Result<(), CliError> {
    let crate_name = format!("kani-{id}");
    let dir = Path::new(&crate_name);
    if dir.exists() {
        return Err(CliError::Other(format!("{crate_name} already exists")));
    }
    std::fs::create_dir_all(dir.join("src"))?;

    let cargo_toml = format!(
        r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2024"

[package.metadata]
id = "{id}"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
kani-shared = {{ path = "../kani-shared", features = ["meta"] }}
"#
    );
    std::fs::write(dir.join("Cargo.toml"), cargo_toml)?;

    let lib_rs = format!(
        r#"use kani_shared::bindings::exports::kani::extension::manga_provider::Guest;
use kani_shared::{{
    ExtensionMetadata, ExtensionResult, MangaExtension, MangaStatus, bindings, ext_version,
    to_shared_filters, types::ActiveFilter, wit_types,
}};
use wit_types::{{Chapter, ChapterList, MangaInfo, MangaList, PreferenceSpec}};

kani_shared::guest_alloc!();

pub struct {struct_name} {{
    _base_url: String,
}}

impl Default for {struct_name} {{
    fn default() -> Self {{
        Self::new()
    }}
}}

impl {struct_name} {{
    pub fn new() -> Self {{
        Self {{
            _base_url: "https://TODO.example.com".to_string(),
        }}
    }}

    pub fn metadata() -> ExtensionMetadata {{
        ExtensionMetadata {{
            id: "{id}".to_string(),
            name: "{name}".to_string(),
            version: ext_version!("0.1.0"),
            base_url: "https://TODO.example.com".to_string(),
            language: "en".to_string(),
            nsfw: false,
            unrestricted_http: false,
            mihon_source_id: None,
            rate_limit: None,
            ..Default::default()
        }}
    }}
}}

impl Guest for {struct_name} {{
    fn get_metadata() -> Result<String, wit_types::ExtensionError> {{
        Ok(kani_shared::serde_json::to_string(&{struct_name}::metadata())
            .expect("ExtensionMetadata serializes to JSON"))
    }}

    fn get_popular_manga(
        page: i32,
        page_size: i32,
        filters: Vec<wit_types::ActiveFilter>,
    ) -> Result<MangaList, wit_types::ExtensionError> {{
        let shared = to_shared_filters(filters);
        get_extension()
            .get_popular_manga(page, page_size, &shared)
            .map_err(|e| e.into_wit())
    }}

    fn search_manga(
        query: String,
        page: i32,
        page_size: i32,
        filters: Vec<wit_types::ActiveFilter>,
    ) -> Result<MangaList, wit_types::ExtensionError> {{
        let shared = to_shared_filters(filters);
        get_extension()
            .search_manga(&query, page, page_size, &shared)
            .map_err(|e| e.into_wit())
    }}

    fn get_filter_list() -> Result<wit_types::FilterList, wit_types::ExtensionError> {{
        get_extension().get_filter_list().map_err(|e| e.into_wit())
    }}

    fn get_fetched_option_sets() -> Result<String, wit_types::ExtensionError> {{
        get_extension()
            .get_fetched_option_sets()
            .map_err(|e| e.into_wit())
    }}

    fn get_manga_details(manga_id: String) -> Result<MangaInfo, wit_types::ExtensionError> {{
        get_extension()
            .get_manga_details(&manga_id)
            .map_err(|e| e.into_wit())
    }}

    fn get_chapter_list(
        manga_id: String,
        page: i32,
        page_size: Option<i32>,
        sort: Option<String>,
    ) -> Result<ChapterList, wit_types::ExtensionError> {{
        get_extension()
            .get_chapter_list(&manga_id, page, page_size, sort)
            .map_err(|e| e.into_wit())
    }}

    fn get_chapter_sort_list() -> Result<Vec<wit_types::SortOption>, wit_types::ExtensionError> {{
        get_extension()
            .get_chapter_sort_list()
            .map_err(|e| e.into_wit())
    }}

    fn get_pages(
        manga_id: String,
        chapter_id: String,
    ) -> Result<Chapter, wit_types::ExtensionError> {{
        get_extension()
            .get_pages(&manga_id, &chapter_id)
            .map_err(|e| e.into_wit())
    }}

    fn get_preferences() -> Result<Vec<PreferenceSpec>, wit_types::ExtensionError> {{
        get_extension().get_preferences().map_err(|e| e.into_wit())
    }}

    fn get_url(manga_id: String) -> Result<String, wit_types::ExtensionError> {{
        get_extension().get_url(&manga_id).map_err(|e| e.into_wit())
    }}
}}

impl MangaExtension for {struct_name} {{
    fn name(&self) -> &str {{
        "{name}"
    }}

    fn get_popular_manga(
        &self,
        _page: i32,
        _page_size: i32,
        _filters: &[ActiveFilter],
    ) -> ExtensionResult<MangaList> {{
        Ok(MangaList {{
            manga: vec![],
            has_next_page: false,
            total_pages: None,
        }})
    }}

    fn search_manga(
        &self,
        _query: &str,
        _page: i32,
        _page_size: i32,
        _filters: &[ActiveFilter],
    ) -> ExtensionResult<MangaList> {{
        Ok(MangaList {{
            manga: vec![],
            has_next_page: false,
            total_pages: None,
        }})
    }}

    fn get_manga_details(&self, manga_id: &str) -> ExtensionResult<MangaInfo> {{
        Ok(MangaInfo {{
            id: manga_id.to_string(),
            title: "{name}".to_string(),
            description: None,
            status: MangaStatus::Unknown,
            authors: vec![],
            artists: vec![],
            tags: vec![],
            cover_url: None,
        }})
    }}

    fn get_chapter_list(
        &self,
        _manga_id: &str,
        _page: i32,
        _page_size: Option<i32>,
        _sort: Option<String>,
    ) -> ExtensionResult<ChapterList> {{
        Ok(ChapterList {{
            chapters: vec![],
            has_next_page: false,
            total_pages: None,
        }})
    }}

    fn get_pages(&self, _manga_id: &str, _chapter_id: &str) -> ExtensionResult<Chapter> {{
        Ok(Chapter {{ pages: vec![] }})
    }}

    fn get_filter_list(&self) -> ExtensionResult<wit_types::FilterList> {{
        Ok(wit_types::FilterList {{ filters: vec![] }})
    }}

    fn get_preferences(&self) -> ExtensionResult<Vec<PreferenceSpec>> {{
        Ok(vec![])
    }}

    fn get_chapter_sort_list(&self) -> ExtensionResult<Vec<wit_types::SortOption>> {{
        Ok(vec![])
    }}
}}

use std::sync::OnceLock;

static EXTENSION: OnceLock<{struct_name}> = OnceLock::new();

fn get_extension() -> &'static {struct_name} {{
    EXTENSION.get_or_init({struct_name}::new)
}}

bindings::export!({struct_name});
"#
    );
    std::fs::write(dir.join("src/lib.rs"), lib_rs)?;

    println!(
        "Created {crate_name}/ — add it to the workspace members, implement the trait methods, \
         then run `kani-cli build {crate_name}`"
    );
    Ok(())
}
