use crate::error::CliError;
use std::path::Path;

pub fn run(name: &str) -> Result<(), CliError> {
    let filename = format!("{name}.yaml");
    let path = Path::new(&filename);

    if path.exists() {
        return Err(CliError::Other(format!("{filename} already exists")));
    }

    let id = name.replace(' ', "-").to_lowercase();
    let struct_name = id
        .split('-')
        .map(|p| {
            let mut c = p.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect::<String>();

    let content = format!(
        r#"# Kani declarative extension: {struct_name}
# Generated by `kani-cli new {name}` — fill in the TODOs and run `kani-cli validate {filename}`.

id: {id}
name: {struct_name}
version: "0.1.0"
base_url: "https://TODO.example.com"
language: en
nsfw: false
unrestricted_http: false

endpoints:
  popular:
    delegate_to: search
    empty_without_filters: false

  search:
    route: "/TODO/search"
    queries:
      q: $query$
    pagination:
      native_page_size: 20
      offset_param: "page"
      offset_type: page
      page_start: 1
    container: "TODO"
    fields:
      id: 'self.attr("href").split("/").at(-1)'
      title: 'self.first("h2").text()'
      cover_url:
        expr: 'self.first("img").attr("src")'
        optional: true

  manga_details:
    route: "/TODO/$manga_id$"
    container: ":root"
    fields:
      id: '"$manga_id$"'
      title: 'dom("h1").text()'
      status: 'dom(".status").text().lower().lookup({{"ongoing": "ongoing", "completed": "completed"}}).fallback("unknown")'
      cover_url:
        expr: 'dom("img.cover").attr("src")'
        optional: true
      description:
        expr: 'dom(".description").text()'
        optional: true
      authors: '["Unknown"]'
      artists: '["Unknown"]'
      tags:
        expr: 'self.select(".tag").map($item.text().trim())'
        optional: true

  chapter_list:
    route: "/TODO/$manga_id$"
    container: "TODO"
    has_next_page: false
    fields:
      id: 'self.attr("href").split("/").at(-1)'
      number: 'self.text().trim().parse_float().fallback(0.0)'
      title:
        expr: "null"
        optional: true
      volume:
        expr: "null"
        optional: true
      scanlator:
        expr: "null"
        optional: true
      date_uploaded:
        expr: "null"
        optional: true
      language: '"en"'

  pages:
    route: "/TODO/$chapter_id$"
    container: "img"
    fields:
      index: "index()"
      url: 'self.attr("src")'

filters: []
preferences: []
"#
    );

    std::fs::write(path, content)?;
    println!("Created {filename} — edit it and run `kani-cli validate {filename}`");
    Ok(())
}
