[package]
name = "kani-fixture-source"
version = "0.1.0"
license.workspace = true
edition = "2024"

[lints.clippy]
unwrap_used = { level = "deny", priority = 1 }

[package.metadata]
id = "fixture"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
kani-shared = { path = "../../kani-shared", features = ["builder"] }
