use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Kani API",
        version = env!("CARGO_PKG_VERSION"),
        description = "REST API for Kani — a self-hosted manga/comics server.",
        license(name = "MIT"),
    ),
    paths(
        // system
        crate::rest::system::system_info,
        crate::rest::system::system_changelog,
        crate::rest::system::complete_first_run,
        crate::rest::admin::system_capabilities,
        // auth
        crate::rest::auth::auth_login,
        crate::rest::auth::auth_logout,
        crate::rest::auth::auth_me,
        crate::rest::auth::get_current_user,
        crate::rest::auth::change_password,
        crate::rest::auth::logout_everywhere,
        crate::rest::auth::list_sessions,
        crate::rest::auth::revoke_all_other_sessions,
        crate::rest::auth::revoke_session,
        crate::rest::auth::totp_setup,
        crate::rest::auth::totp_verify,
        crate::rest::auth::get_features,
        crate::rest::auth::get_my_permissions,
        crate::rest::auth::get_registration_enabled,
        crate::rest::auth::auth_register,
        crate::rest::auth::get_password_reset_enabled,
        crate::rest::auth::password_reset_request,
        crate::rest::auth::password_reset_confirm,
        crate::rest::auth::password_strength,
        crate::rest::auth::totp_disable,
        crate::rest::auth::totp_regenerate_backup_codes,
        crate::rest::auth::totp_step_up,
        crate::rest::auth::get_captcha,
        crate::rest::auth::password_reset_validate,
        crate::rest::auth::verify_email,
        crate::rest::auth::resend_verification,
        // settings
        crate::rest::settings::get_settings,
        crate::rest::settings::toggle_auto_scan,
        crate::rest::settings::start_refresh_all_rest,
        crate::rest::settings::get_refresh_status,
        // library
        crate::rest::library::get_library_filtered,
        crate::rest::library::get_library,
        crate::rest::library::scan_all_library,
        crate::rest::library::scan_manga_multiple,
        crate::rest::library::get_continue_reading_shelf,
        crate::rest::library::library_backup,
        crate::rest::library::library_backup_preview,
        crate::rest::library::library_restore,
        crate::rest::library::library_tachiyomi_preview,
        crate::rest::library::library_import_tachiyomi,
        crate::rest::library::library_pending_imports,
        crate::rest::library::library_delete_pending_import,
        crate::rest::library::library_resolve_pending_import,
        crate::rest::library::library_orphaned,
        crate::rest::library::library_duplicates,
        crate::rest::library::library_merge_duplicate,
        crate::rest::library::library_duplicates_scan,
        crate::rest::library::library_dismiss_duplicate,
        crate::rest::library::get_recent_updates,
        crate::rest::library::global_search_handler,
        // categories
        crate::rest::categories::list_categories,
        crate::rest::categories::create_category,
        crate::rest::categories::reorder_categories,
        crate::rest::categories::rename_category,
        crate::rest::categories::delete_category_handler,
        crate::rest::categories::get_manga_categories,
        crate::rest::categories::set_manga_categories,
        // manga
        crate::rest::manga::get_manga,
        crate::rest::manga::delete_manga,
        crate::rest::manga::upload_manga_cover_handler,
        crate::rest::manga::clear_manga_cover_handler,
        crate::rest::manga::get_local_manga_details,
        crate::rest::manga::get_local_chapters,
        crate::rest::manga::get_chapter_ids,
        crate::rest::manga::download_all,
        crate::rest::manga::cancel_all_downloads,
        crate::rest::manga::refresh_manga,
        crate::rest::manga::scan_manga,
        crate::rest::manga::toggle_auto_download,
        crate::rest::manga::toggle_auto_scan_manga,
        crate::rest::manga::toggle_download_all_preferred,
        crate::rest::manga::update_manga_notes,
        crate::rest::manga::update_local_metadata_handler,
        crate::rest::manga::mark_manga_seen,
        crate::rest::manga::preview_migration,
        crate::rest::manga::migrate_manga_handler,
        crate::rest::manga::get_download_rules,
        crate::rest::manga::add_download_rule,
        crate::rest::manga::delete_download_rule,
        crate::rest::manga::update_download_rule,
        crate::rest::manga::reorder_download_rules,
        crate::rest::manga::preview_download_rules,
        crate::rest::manga::enrich_metadata_handler,
        crate::rest::manga::trigger_chapter_stream,
        // scanlators
        crate::rest::scanlators::get_scanlator_prefs,
        crate::rest::scanlators::set_scanlator_pref,
        crate::rest::scanlators::delete_scanlator_pref,
        crate::rest::scanlators::set_scanlator_mode_handler,
        crate::rest::scanlators::get_chapter_scanlators,
        crate::rest::scanlators::get_chapter_languages,
        // chapters
        crate::rest::chapters::get_chapter_page_manifest,
        crate::rest::chapters::set_chapter_progress_handler,
        crate::rest::chapters::get_bookmarks_handler,
        crate::rest::chapters::toggle_bookmark_handler,
        crate::rest::chapters::get_chapter_note_handler,
        crate::rest::chapters::set_chapter_note_handler,
        crate::rest::chapters::get_manga_chapter_notes_handler,
        crate::rest::chapters::set_chapter_read_status_handler,
        crate::rest::chapters::get_continue_reading_handler,
        crate::rest::chapters::mark_chapters_up_to_handler,
        // downloads
        crate::rest::downloads::get_download_history,
        crate::rest::downloads::start_download,
        crate::rest::downloads::delete_downloaded,
        crate::rest::downloads::cancel_download,
        crate::rest::downloads::cancel_all_global_downloads,
        // export
        crate::rest::export::serve_chapter_cbz,
        crate::rest::export::export_epub,
        crate::rest::export::export_kepub,
        crate::rest::export::export_kcc,
        // stats
        crate::rest::stats::reading_stats,
        crate::rest::stats::reading_pace_handler,
        // sources
        crate::rest::sources::list_sources,
        crate::rest::sources::add_source,
        crate::rest::sources::get_sources_health,
        crate::rest::sources::get_active_source_ids,
        crate::rest::sources::list_metadata_providers,
        crate::rest::sources::get_source,
        crate::rest::sources::update_source,
        crate::rest::sources::delete_source,
        crate::rest::sources::get_metadata,
        crate::rest::sources::upload_wasm,
        crate::rest::sources::fetch_wasm,
        crate::rest::sources::install_yaml,
        crate::rest::sources::fetch_yaml,
        crate::rest::sources::reload_source_handler,
        crate::rest::sources::get_popular_manga,
        crate::rest::sources::search_manga,
        crate::rest::sources::get_manga_details,
        crate::rest::sources::get_source_manga_url,
        crate::rest::sources::save_to_library,
        crate::rest::sources::get_chapter_list,
        crate::rest::sources::get_chapter_sort_list,
        crate::rest::sources::get_pages,
        crate::rest::sources::check_in_library,
        crate::rest::sources::toggle_source_enabled,
        crate::rest::sources::toggle_source_favourite,
        crate::rest::sources::get_source_filters,
        crate::rest::sources::get_pref_schema,
        crate::rest::sources::get_source_preferences,
        crate::rest::sources::set_source_preference,
        crate::rest::sources::append_pref_list_item,
        crate::rest::sources::remove_pref_list_item,
        crate::rest::sources::toggle_pref_select_item,
        crate::rest::sources::get_capabilities,
        // trackers
        crate::rest::trackers::get_manga_tracking_handler,
        crate::rest::trackers::set_manga_tracking_handler,
        crate::rest::trackers::list_trackers,
        crate::rest::trackers::get_tracker_auth_url,
        crate::rest::trackers::tracker_oauth_callback,
        crate::rest::trackers::unlink_tracker,
        crate::rest::trackers::search_tracker_manga,
        crate::rest::trackers::get_tracker_config,
        crate::rest::trackers::set_tracker_config,
        crate::rest::trackers::delete_tracker_config,
        crate::rest::trackers::get_tracker_mappings,
        crate::rest::trackers::set_tracker_mapping,
        crate::rest::trackers::delete_tracker_mapping,
        crate::rest::trackers::sync_all_trackers,
        crate::rest::trackers::sync_manga_trackers,
        // webhooks
        crate::rest::webhooks::list_webhooks,
        crate::rest::webhooks::create_webhook,
        crate::rest::webhooks::update_webhook,
        crate::rest::webhooks::delete_webhook,
        crate::rest::webhooks::test_webhook,
        crate::rest::webhooks::list_webhook_deliveries,
        crate::rest::webhooks::get_manga_webhook_notify,
        crate::rest::webhooks::set_manga_webhook_notify,
        // admin
        crate::rest::admin::server_stop,
        crate::rest::admin::server_restart,
        crate::rest::admin::admin_list_users,
        crate::rest::admin::admin_create_user,
        crate::rest::admin::admin_update_user,
        crate::rest::admin::admin_delete_user,
        crate::rest::admin::admin_grant_role,
        crate::rest::admin::admin_revoke_role,
        crate::rest::admin::admin_user_activity,
        crate::rest::admin::admin_list_roles,
        crate::rest::admin::admin_create_role,
        crate::rest::admin::admin_update_role,
        crate::rest::admin::admin_delete_role,
        crate::rest::admin::run_maintenance,
        crate::rest::admin::db_stats,
        crate::rest::admin::db_analyze,
        crate::rest::admin::db_vacuum,
        crate::rest::admin::clear_cache,
        crate::rest::admin::stop_scan,
        crate::rest::admin::admin_send_test_email,
        crate::rest::admin::admin_trigger_password_reset_handler,
        crate::rest::admin::get_credential_encryption_status_handler,
        crate::rest::admin::migrate_credentials_handler,
        crate::rest::admin::admin_logs,
        crate::rest::admin::admin_logs_stream,
        crate::rest::admin::admin_logs_download,
        crate::rest::admin::admin_purge_logs,
        crate::rest::admin::admin_audit_log,
        crate::rest::admin::admin_audit_log_download,
        crate::rest::admin::fs_browse_handler,
        crate::rest::admin::fs_mkdir_handler,
        crate::rest::admin::path_migrate_estimate_handler,
        crate::rest::admin::path_migrate_handler,
    ),
    components(
        schemas(
            crate::models::LoginRequest,
            crate::models::SetChapterProgressRequest,
            crate::models::ChangePasswordRequest,
            crate::models::CreateSource,
            crate::models::UpdateSource,
            crate::models::FetchWasmRequest,
            crate::models::InstallYamlRequest,
            crate::models::FetchYamlRequest,
            crate::models::SearchMangaRequest,
            crate::models::UpdateLocalMetadataRequest,
            crate::models::AddDownloadRuleRequest,
            crate::models::UpdateDownloadRuleRequest,
            crate::models::ReorderDownloadRulesRequest,
            crate::models::PreviewDownloadRulesRequest,
            crate::models::ToggleEnabledRequest,
            crate::models::ToggleFavouritedRequest,
            crate::models::ToggleAutoDownloadRequest,
            crate::models::PreviewMigrationRequest,
            crate::models::MigrateMangaRequest,
            crate::models::CreateCategoryRequest,
            crate::models::RenameCategoryRequest,
            crate::models::ReorderCategoriesRequest,
            crate::models::SetMangaCategoriesRequest,
            crate::models::SetScanlatorPrefRequest,
            crate::models::SetScanlatorModeRequest,
            crate::models::SetReadStatusRequest,
            crate::models::SetMangaTrackingRequest,
            crate::models::ToggleBookmarkRequest,
            crate::models::SetChapterNoteRequest,
            crate::models::MarkUpToRequest,
            crate::models::ScanMangaRequest,
            crate::models::SetPreferenceRequest,
            crate::models::ListItemRequest,
            crate::models::ToggleSelectRequest,
            crate::models::SetTrackerConfigRequest,
            crate::models::SetTrackerMappingRequest,
            crate::models::AdminCreateUserRequest,
            crate::models::AdminUpdateUserRequest,
            crate::models::AdminGrantRoleRequest,
            crate::models::AdminCreateRoleRequest,
            crate::models::AdminUpdateRoleRequest,
            crate::models::PasswordResetRequestBody,
            crate::models::PasswordResetConfirmBody,
            crate::models::SendTestEmailBody,
            crate::rest::TotpCodeRequest,
            crate::rest::RegisterRequest,
        )
    ),
    tags(
        (name = "system", description = "Server info, first-run onboarding, and settings"),
        (name = "auth", description = "Authentication, sessions, TOTP, and password management"),
        (name = "library", description = "Library listing, scanning, backup/restore, and categories"),
        (name = "manga", description = "Per-manga operations, tracking, scanlators, and download rules"),
        (name = "chapters", description = "Chapter reading, progress, bookmarks, downloads, and exports"),
        (name = "sources", description = "Extension source management and browsing"),
        (name = "admin", description = "User/role administration, logs, audit, and server management"),
    ),
)]
pub struct ApiDoc;
