[package]
name = "kani-yaml"
version = "1.0.0-rc.2"
license.workspace = true
repository.workspace = true
edition = "2024"

[lints]
workspace = true

[lib]
name = "kani_yaml"
path = "src/lib.rs"

[dependencies]
kani-shared = { path = "../kani-shared", features = ["builder"] }
serde       = { version = "1", features = ["derive"] }
serde_yaml  = "0.9"
chumsky     = "1.0.0-alpha.8"
thiserror   = "2.0"
rhai        = { version = "1.19", features = ["sync"] }
base64      = "0.22"
semver      = "1"
